import type { Property } from '@/lib/types';
import { placeholderImages } from '@/lib/placeholder-images';

export const properties: Property[] = [
  {
    propertyId: 'p001',
    title: 'Serene Residential Plot in Wagholi',
    ownerName: 'BrickAi Realty',
    source: 'BrickAi Project',
    surveyNumber: '123/4A',
    gatNumber: 'G-56',
    plotNumber: 'P-15',
    landType: 'Residential',
    village: 'Wagholi',
    city: 'Pune',
    taluka: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '412207',
    latitude: 18.5913,
    longitude: 73.9929,
    areaSqFt: 2500,
    boundaryDescription: 'Fenced on all sides, adjacent to 20ft road.',
    roadAccess: true,
    cornerPlot: true,
    documents: [
      { documentId: 'd001', documentType: '7/12', documentFileUrl: '#', uploadedAt: '2023-10-15' },
      { documentId: 'd002', documentType: 'Registry', documentFileUrl: '#', uploadedAt: '2023-10-15' },
    ],
    verificationStatus: 'VERIFIED',
    verificationNote: 'All documents verified by BrickAi legal team. Title is clear.',
    price: 7500000,
    pricePerSqFt: 3000,
    createdAt: '2023-01-01',
    updatedAt: '2023-11-20',
    createdByUserId: 'system',
    imageUrl: placeholderImages['property-1'].imageUrl,
    imageHint: placeholderImages['property-1'].imageHint,
    amenities: [
      { name: 'Lifepoint Hospital', category: 'Hospital', distance: 2.5, travelTime: 10, rating: 4.5, address: 'Wagholi, Pune' },
      { name: 'Podar International School', category: 'School', distance: 1.2, travelTime: 5, rating: 4.8, address: 'Wagholi, Pune' },
      { name: 'Reliance Fresh', category: 'Grocery', distance: 0.8, travelTime: 3, rating: 4.2, address: 'Near EON IT Park' },
    ],
    priceHistory: [
        { date: '2022-01', price: 6500000 },
        { date: '2022-07', price: 6800000 },
        { date: '2023-01', price: 7200000 },
        { date: '2023-07', price: 7500000 },
    ],
  },
  {
    propertyId: 'p002',
    title: 'Prime Agricultural Land near Hinjewadi',
    ownerName: 'Ramesh Patel',
    source: 'Individual Owner',
    surveyNumber: '88/B',
    gatNumber: 'G-101',
    plotNumber: 'N/A',
    landType: 'Agricultural',
    village: 'Marunji',
    city: 'Pune',
    taluka: 'Mulshi',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '411057',
    latitude: 18.5944,
    longitude: 73.704,
    areaSqFt: 43560, // 1 Acre
    boundaryDescription: 'Natural stream on the east, road on the west.',
    roadAccess: true,
    cornerPlot: false,
    documents: [
      { documentId: 'd003', documentType: '7/12', documentFileUrl: '#', uploadedAt: '2023-05-10' },
    ],
    verificationStatus: 'USER_DECLARED',
    verificationNote: 'Owner has uploaded 7/12 extract. Verification is pending.',
    price: 15000000,
    pricePerSqFt: 344.35,
    createdAt: '2023-05-10',
    updatedAt: '2023-11-15',
    createdByUserId: 'u123',
    imageUrl: placeholderImages['property-4'].imageUrl,
    imageHint: placeholderImages['property-4'].imageHint,
     amenities: [
      { name: 'Hinjewadi IT Park', category: 'Transport', distance: 5.0, travelTime: 15, rating: 4.0, address: 'Hinjewadi, Pune' },
      { name: 'Sanjivani Hospital', category: 'Hospital', distance: 4.5, travelTime: 12, rating: 4.1, address: 'Marunji, Pune' },
      { name: 'D-Mart', category: 'Grocery', distance: 6.0, travelTime: 20, rating: 4.4, address: 'Hinjewadi Phase 1' },
    ],
    priceHistory: [
        { date: '2022-01', price: 12000000 },
        { date: '2022-07', price: 13500000 },
        { date: '2023-01', price: 14000000 },
        { date: '2023-07', price: 15000000 },
    ],
  },
  {
    propertyId: 'p003',
    title: 'NA Plot in Verified Developer Project',
    ownerName: 'FutureScapes Developers',
    source: 'Verified Developer',
    surveyNumber: '210',
    gatNumber: 'G-22',
    plotNumber: 'P-88',
    landType: 'NA',
    village: 'Charholi Budruk',
    city: 'Pune',
    taluka: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '412105',
    latitude: 18.644,
    longitude: 73.882,
    areaSqFt: 1800,
    boundaryDescription: 'Located within a gated community with internal roads.',
    roadAccess: true,
    cornerPlot: false,
    documents: [
      { documentId: 'd004', documentType: 'Sale Deed', documentFileUrl: '#', uploadedAt: '2022-12-01' },
      { documentId: 'd005', documentType: '7/12', documentFileUrl: '#', uploadedAt: '2022-12-01' },
    ],
    verificationStatus: 'PARTIALLY_VERIFIED',
    verificationNote: 'Developer credentials and project RERA are verified. Individual plot documents are being processed.',
    price: 4500000,
    pricePerSqFt: 2500,
    createdAt: '2022-12-01',
    updatedAt: '2023-11-22',
    createdByUserId: 'd-dev-1',
    imageUrl: placeholderImages['property-2'].imageUrl,
    imageHint: placeholderImages['property-2'].imageHint,
    amenities: [
      { name: 'DY Patil College of Engineering', category: 'School', distance: 3.0, travelTime: 10, rating: 4.6, address: 'Akurdi, Pune' },
      { name: 'Pune Metro - PCMC Station', category: 'Transport', distance: 7.0, travelTime: 25, rating: 4.7, address: 'Pimpri-Chinchwad' },
      { name: 'City Central Mall', category: 'Grocery', distance: 6.5, travelTime: 22, rating: 4.3, address: 'Pimpri' },
    ],
    priceHistory: [
        { date: '2022-01', price: 3800000 },
        { date: '2022-07', price: 4000000 },
        { date: '2023-01', price: 4200000 },
        { date: '2023-07', price: 4500000 },
    ],
  },
];
