// This file defines the Genkit flow for AI house planning, allowing users to generate conceptual house plans based on their property details and preferences.

'use server';

/**
 * @fileOverview AI house planning flow.
 *
 * - aiHousePlanning - A function that handles the AI house planning process.
 * - AiHousePlanningInput - The input type for the aiHousePlanning function.
 * - AiHousePlanningOutput - The return type for the aiHousePlanning function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiHousePlanningInputSchema = z.object({
  propertyDetails: z.string().describe('Details of the property for which the house plan is being generated.'),
  floors: z.number().describe('Number of floors in the house plan.'),
  rooms: z.number().describe('Number of rooms in the house plan.'),
  budgetRange: z.string().describe('Budget range for the house construction.'),
  purpose: z.string().describe('Purpose of the house (self-use / rental).'),
  stylePreference: z.string().optional().describe('Optional style preferences for the house design.'),
  vastuPreference: z.string().optional().describe('Optional Vastu preferences for the house design.'),
});
export type AiHousePlanningInput = z.infer<typeof AiHousePlanningInputSchema>;

const AiHousePlanningOutputSchema = z.object({
  layout: z.string().describe('Basic layout of the house plan.'),
  roomDistribution: z.string().describe('Room distribution in the house plan.'),
  orientationNotes: z.string().describe('Orientation notes for the house plan.'),
  placeholder3DImage: z.string().describe('Placeholder 3D image URL representing the house plan.'),
  disclaimer: z
    .string()
    .default('This is a concept design generated by AI. Final approval required from licensed professionals.')
    .describe('Disclaimer for the AI-generated house plan.'),
});
export type AiHousePlanningOutput = z.infer<typeof AiHousePlanningOutputSchema>;

export async function aiHousePlanning(input: AiHousePlanningInput): Promise<AiHousePlanningOutput> {
  return aiHousePlanningFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiHousePlanningPrompt',
  input: {schema: AiHousePlanningInputSchema},
  output: {schema: AiHousePlanningOutputSchema},
  prompt: `You are an AI house planning assistant. Generate a conceptual house plan based on the following details:

Property Details: {{{propertyDetails}}}
Number of Floors: {{{floors}}}
Number of Rooms: {{{rooms}}}
Budget Range: {{{budgetRange}}}
Purpose: {{{purpose}}}
Style Preference: {{{stylePreference}}}
Vastu Preference: {{{vastuPreference}}}

Consider important building constraints to generate the layout and room distribution.

Output:
Layout: 
Room Distribution:
Orientation Notes:
3D Image: A URL for a placeholder 3D image mock-up.
Disclaimer: This is a concept design generated by AI. Final approval required from licensed professionals.`,
});

const aiHousePlanningFlow = ai.defineFlow(
  {
    name: 'aiHousePlanningFlow',
    inputSchema: AiHousePlanningInputSchema,
    outputSchema: AiHousePlanningOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
